### ISSUE TITLE
Edge embedding enquiry

### ISSUE THREAD

**Issue by amblee0306** [maxiaoba/GRAPE#4]
<img width="500" alt="Screenshot 2021-01-22 at 1 10 37 PM" src="https://user-images.githubusercontent.com/19768905/105449451-69459000-5cb3-11eb-99be-4d2a41147c94.png">

Hi there, 

I would like to clarify the value of the edge embedding when the value in D (the feature matrix) of that specific edge is missing in the bipartite graph. And what is the network utilised for O_edge to obtain a prediction of D_hat.  

Thanks

**Comment by maxiaoba** [comment]
No edge exists for the missing values. The edges are only built between observation and feature nodes with known feature values.
O_edge is a network taking input of the concatenation of one observation node embedding and one feature node embedding and output the predicted feature value.
