### ISSUE TITLE
Train with custom dataset

### ISSUE THREAD

**Issue by marcopost-it** [maxiaoba/GRAPE#6]
Hi!
I am trying to apply your approach on my dataset with a lot of missing values, stored as _NaN_ values. I am trying to customize your code, but I think that some your suggestions could be useful to speed up my work. 

I am currently with two dataframes df_X and df_Y as input parameters, df_X being a feature matrix with numerical and NaN values, df_Y being an array of numbers yi = 1, 2 or 3. 

I already tried to use the "get_data" function used for the UCI dataset: the code works, but the training fails (loss is always nan) due to nan values contained in data. I think I should not add the "nan" edges during training, but the lack of comments in code makes it difficult to understand what to change to accomplish this purpose.

Thanks in advance for your help! :)

**Comment by maxiaoba** [comment]
Hi! Good question. Yeah the original code used for UCI dataset is to randomly generate missing masks from a "all known" data matrix. In your case, you could change the line "train_edge_mask = get_known_mask(train_edge_prob, int(edge_attr.shape[0]/2))" in "get_data" function in uci_data.py to your own function which generates a mask that masks out the NaN values.

**Comment by marcopost-it** [comment]
Thank you! The replacement of the line you mentioned with "train_edge_mask = ~torch.any(edge_attr[:int(edge_attr.shape[0]/2)], dim=1)" seems to be a workable solution.

**Comment by zeginis** [comment]
@marcopost-it I also try us GRAPE with my custom dataset. Could you give me some help on what you customized at the current code to make it work? Do you have your solution somewhere public? Thank you in advance.

**Comment by YiChui9** [comment]
@marcopost-it Have you successfully applied this model to a dataset containing NaN values using this strategy? I have attempted to replace the code with "train_edge_mask = ~torch.any(edge_attr[:int(edge_attr.shape[0]/2)], dim=1)", but the program still fails to train (the loss remains NaN). Thank you in advance,hope for your reply.

> Thank you! The replacement of the line you mentioned with "train_edge_mask = ~torch.any(edge_attr[:int(edge_attr.shape[0]/2)], dim=1)" seems to be a workable solution.
